pub const ASSET_API_PREFIX: &str = "/api/asset/assets";
pub const ASSET_PROPERTIES_API_PREFIX: &str = "/api/asset/assetProperties";
pub const CUSTOM_ASSET_PROPERTIES_API_PREFIX: &str = "/api/asset/customAssetProperties";

pub const ASSET_TYPES: [&str; 29] = [
    "BladeEnclosure",
    "BladeNetwork",
    "BladeServer",
    "BladeStorage",
    "Busway",
    "Camera",
    "Chiller",
    "Crac",
    "Crah",
    "Environmental",
    "FireControlPanel",
    "Generator",
    "InRowCooling",
    "KvmSwitch",
    "Location",
    "Monitor",
    "NetworkDevice",
    "NetworkStorage",
    "NodeServer",
    "PatchPanel",
    "PduAndRpp",
    "PowerMeter",
    "Rack",
    "RackPdu",
    "Server",
    "SmallUps",
    "TransferSwitch",
    "Ups",
    "VirtualServer",
];
